# Basic settings
url: "https://objective-swanson-e8357b.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Advogado RJ - Sabino Rocha Advogados Associados" # the name of your site, e.g. ACME Corp.
description: "Sabino Rocha Advogados Associados é um escritório localizado no Rio de Janeiro, 
com forte atuação nas áreas cível, família, criminal e imobiliário."
tagline: "Advogado, Advogado RJ, Advogados"
lang: "pt-BR"
# Build settings
markdown: kramdown

# Kramdown options
kramdown:
  # Prevent IDs from being added to h1-h6 tags
  auto_ids: false

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-menus
 
  
#paginate: 3
#paginate_path: service/page:num/
paginate: 3
paginate_path: posts/page:num/

#Permalink
permalink: /post/:title
source: .
destination: ./_site
# Compress CSS
sass:
  style: :compressed
  sass_dir: _sass



#Collections
collections:
 
  expertise:
include:
  - _pages
  - _posts
  - _expertise
section: true

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: false

# set to 'true' to enable Google Analytics tracking code in production builds
analytics: false

# Compress HTML (in liquid via layouts/compress.html)
compress_html:
  clippings: all

# Social

social:
  name: Sabinorocha
  links:
    - https://twitter.com/sabinorocha
    - https://www.facebook.com/sabinorocha

# set some common post defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post" # set the correct default template for a post
      section: "post" # set the root section name

# Include in processing (e.g. Netlify directives)
# Uncomment before use

#include:
#  - _redirects
#  - _headers

# Exclude from processing.
# The following items will not be processed.
exclude:
  - README.md
  - LICENSE.txt
  - netlify.toml
  - feed.xml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
